BEGIN;

DELETE FROM user_profile
WHERE telegram_id = 123;

WITH profile_insert AS (
    INSERT INTO user_profile (
        telegram_id,
        username,
        first_name,
        last_name,
        goal_text,
        direction,
        specific_track,
        target_role,
        goal_reason,
        current_level,
        time_per_week_label,
        time_per_week_value,
        preferred_formats,
        wishes,
        preference_json,
        notification_settings_json,
        global_xp,
        streak_days,
        streak_multiplier,
        last_activity,
        dialog_state,
        profile_json
    )
    VALUES (
        123,
        'test_progressor',
        'Тестовый',
        'Пользователь',
        'Стать Python backend разработчиком и собрать pet-project',
        'programming',
        'python_backend',
        'python backend developer',
        'Хочу уверенно делать API, работать с PostgreSQL и Docker.',
        'basic',
        '3-7 часов',
        6,
        ARRAY['video', 'practice', 'article'],
        'Больше практики, короткие материалы, без слишком длинных видео.',
        '{
            "collected": true,
            "hard_rules": ["free_or_official_materials"],
            "soft_rules": ["prefer_practice", "avoid_long_videos"],
            "blocked_authors": [],
            "blocked_channels": [],
            "blocked_sources": [],
            "preferred_sources": ["docs", "interactive_tasks", "short_video"],
            "format_weights": {
                "video": 0.8,
                "article": 1.1,
                "practice": 1.5
            },
            "max_video_minutes": 20,
            "explanation_style": ["step_by_step", "examples_first"],
            "pace_preference": "short_steps"
        }'::JSONB,
        '{
            "push_enabled": true,
            "motivation_style": "duolingo_aggressive",
            "quiet_hours": {
                "enabled": true,
                "start": "22:00",
                "end": "09:00"
            },
            "max_pushes_per_day": 3,
            "deadline_pushes": true,
            "streak_pushes": true,
            "xp_pushes": true,
            "allow_roast": true
        }'::JSONB,
        280,
        4,
        1.2,
        CURRENT_DATE,
        'roadmap_ready',
        '{
            "mock": true,
            "avatar_color": "#E30613",
            "city": "Tomsk",
            "ai_master": {
                "name": "AI Master",
                "tone": "direct",
                "last_summary": "Ты закрыл первые 3 шага. Сейчас фокус на 4 шаге: схема БД и связи."
            }
        }'::JSONB
    )
    RETURNING user_id
),
roadmap_insert AS (
    INSERT INTO roadmap (
        profile_id,
        title,
        direction,
        target_role,
        level,
        estimated_duration_weeks,
        hours_per_week_label,
        route_logic,
        status,
        version,
        roadmap_json
    )
    SELECT
        user_id,
        'Python Backend: FastAPI + PostgreSQL',
        'programming',
        'python backend developer',
        'basic',
        5,
        '3-7 часов',
        'mock_seed_for_frontend',
        'active',
        1,
        '{
            "mock": true,
            "goal": "Собрать backend pet-project для портфолио",
            "milestones": [
                "Освежить Python и HTTP",
                "Освоить SQL/PostgreSQL",
                "Собрать API на FastAPI",
                "Упаковать проект в Docker"
            ],
            "ai_master_message": "Держим темп: закрывай один небольшой шаг за сессию и фиксируй результат."
        }'::JSONB
    FROM profile_insert
    RETURNING roadmap_id, profile_id
),
items_insert AS (
    INSERT INTO roadmap_item (
        roadmap_id,
        profile_id,
        step_order,
        skill_name,
        topic_name,
        name,
        description,
        resources,
        source_type,
        source_name,
        is_free,
        language,
        difficulty,
        duration_minutes,
        estimated_hours,
        why_this_material,
        skill_result,
        career_value,
        practice_task,
        self_check_questions,
        completion_check_type,
        completion_check_json,
        min_seconds_before_complete,
        issued_at,
        recommended_deadline_at,
        deadline_at,
        xp,
        pending_xp,
        verified_xp,
        xp_policy_json,
        fraud_score,
        streak_multiplier,
        status,
        user_note,
        completed_at,
        item_json
    )
    SELECT
        r.roadmap_id,
        r.profile_id,
        v.step_order,
        v.skill_name,
        v.topic_name,
        v.name,
        v.description,
        v.resources,
        v.source_type,
        v.source_name,
        true,
        'ru',
        v.difficulty,
        v.duration_minutes,
        v.estimated_hours,
        v.why_this_material,
        v.skill_result,
        v.career_value,
        v.practice_task,
        v.self_check_questions::JSONB,
        v.completion_check_type,
        v.completion_check_json::JSONB,
        v.min_seconds_before_complete,
        now() - INTERVAL '7 days',
        now() + (v.step_order || ' days')::INTERVAL,
        now() + ((v.step_order + 2) || ' days')::INTERVAL,
        v.xp,
        v.pending_xp,
        v.verified_xp,
        v.xp_policy_json::JSONB,
        v.fraud_score,
        v.streak_multiplier,
        v.status,
        v.user_note,
        v.completed_at,
        v.item_json::JSONB
    FROM roadmap_insert r
    CROSS JOIN (
        VALUES
            (
                1,
                'Python',
                'Функции, коллекции, модули',
                'Повторить базовый Python',
                'Освежить синтаксис, работу со списками, словарями, функциями и импортами.',
                'https://docs.python.org/3/tutorial/',
                'article',
                'Python Docs',
                'basic',
                45,
                1.0,
                'Фундамент нужен перед API и БД.',
                'Уверенно пишешь небольшие функции и модули.',
                'База для backend-задач и собеседований.',
                'Напиши 5 функций для обработки списка учебных задач.',
                '["Чем list отличается от dict?", "Когда выносить код в функцию?", "Как работает import?"]',
                'quiz',
                '{"type": "quiz", "min_correct": 2, "questions_count": 3}',
                300,
                80,
                80,
                80,
                '{"base_xp": 80, "speed_bonus": false}',
                0,
                1.0,
                'completed',
                'Закрыл быстро, нужно больше практики на словари.',
                now() - INTERVAL '5 days',
                '{"mock": true, "module": "python_basics"}'
            ),
            (
                2,
                'HTTP',
                'HTTP, REST, статусы',
                'Разобрать HTTP и REST',
                'Понять методы, статусы, headers, body и базовый REST-дизайн.',
                'https://developer.mozilla.org/en-US/docs/Web/HTTP/Overview',
                'article',
                'MDN',
                'basic',
                50,
                1.2,
                'Без HTTP API будет магией.',
                'Можешь объяснить, как клиент общается с backend.',
                'Нужно для проектирования endpoint-ов.',
                'Опиши 6 endpoint-ов для API учебного трекера.',
                '["Когда использовать POST?", "Что значит 404?", "Зачем нужны headers?"]',
                'practice',
                '{"type": "short_answer", "required": true}',
                420,
                90,
                90,
                90,
                '{"base_xp": 90}',
                0,
                1.1,
                'completed',
                'Закрыл полностью, endpoint-ы описал.',
                now() - INTERVAL '3 days',
                '{"mock": true, "module": "http"}'
            ),
            (
                3,
                'SQL',
                'SELECT, JOIN, GROUP BY',
                'Потренировать SQL-запросы',
                'Научиться доставать данные из связанных таблиц.',
                'https://sqlbolt.com/',
                'practice',
                'SQLBolt',
                'basic',
                75,
                1.5,
                'Roadmap хранится в PostgreSQL, SQL понадобится сразу.',
                'Пишешь SELECT/JOIN без подсказок.',
                'База для любой backend-роли.',
                'Составь 8 запросов для таблиц user_profile, roadmap, roadmap_item.',
                '["Чем INNER JOIN отличается от LEFT JOIN?", "Как посчитать completed items?", "Зачем GROUP BY?"]',
                'practice',
                '{"type": "sql_tasks", "min_tasks": 5}',
                600,
                110,
                110,
                110,
                '{"base_xp": 110}',
                0,
                1.2,
                'completed',
                'Закрыл SQL-практику на 100%.',
                now() - INTERVAL '1 day',
                '{"mock": true, "module": "sql"}'
            ),
            (
                4,
                'PostgreSQL',
                'Схема БД и связи',
                'Спроектировать таблицы под roadmap',
                'Разобрать PK/FK, индексы, связи один-ко-многим и JSONB.',
                'https://www.postgresql.org/docs/current/tutorial.html',
                'article',
                'PostgreSQL Docs',
                'intermediate',
                90,
                2.0,
                'Фронт и backend завязаны на корректную модель данных.',
                'Можешь объяснить связи между profile, roadmap и item.',
                'Проектирование БД часто спрашивают на junior backend.',
                'Нарисуй схему из 4 таблиц и подпиши связи.',
                '["Что такое foreign key?", "Когда нужен индекс?", "Где уместен JSONB?"]',
                'note',
                '{"type": "note", "min_chars": 300}',
                900,
                120,
                0,
                0,
                '{"base_xp": 120}',
                0,
                1.0,
                'in_progress',
                'Сейчас прохожу шаг 4: схема БД и связи.',
                null,
                '{"mock": true, "module": "postgres_schema"}'
            ),
            (
                5,
                'FastAPI',
                'Pydantic и endpoint-ы',
                'Собрать первый CRUD на FastAPI',
                'Создать GET/POST/PATCH endpoint-ы и подключить Pydantic-схемы.',
                'https://fastapi.tiangolo.com/tutorial/',
                'article',
                'FastAPI Docs',
                'intermediate',
                100,
                2.5,
                'Это основной стек проекта.',
                'Понимаешь request/response модели и validation errors.',
                'FastAPI дает быстрый вход в backend-разработку.',
                'Сделай CRUD для списка учебных задач.',
                '["Что делает response_model?", "Где используется Depends?", "Как FastAPI валидирует body?"]',
                'project',
                '{"type": "mini_project", "required_files": ["main.py", "schemas.py"]}',
                1200,
                140,
                0,
                0,
                '{"base_xp": 140}',
                0,
                1.0,
                'not_started',
                null,
                null,
                '{"mock": true, "module": "fastapi_crud"}'
            ),
            (
                6,
                'Async Python',
                'SQLAlchemy async',
                'Подключить async Postgres',
                'Разобрать async session, SQLAlchemy text-запросы и транзакции.',
                'https://docs.sqlalchemy.org/en/20/orm/extensions/asyncio.html',
                'article',
                'SQLAlchemy Docs',
                'advanced',
                95,
                2.0,
                'Текущий backend использует async SQLAlchemy.',
                'Можешь читать и писать async repository-функции.',
                'Нужный навык для production API.',
                'Добавь repository-функцию для списка roadmaps пользователя.',
                '["Зачем AsyncSession?", "Когда нужен commit?", "Что возвращает mappings()?"]',
                'practice',
                '{"type": "code_task", "min_minutes": 30}',
                1200,
                130,
                0,
                0,
                '{"base_xp": 130}',
                0,
                1.0,
                'not_started',
                null,
                null,
                '{"mock": true, "module": "async_sqlalchemy"}'
            ),
            (
                7,
                'Docker',
                'Docker Compose',
                'Упаковать backend и PostgreSQL',
                'Понять Dockerfile, compose services, volumes и env.',
                'https://docs.docker.com/compose/',
                'article',
                'Docker Docs',
                'intermediate',
                80,
                1.7,
                'Проект уже запускается через Docker Compose.',
                'Можешь поднять backend и БД локально.',
                'Docker почти всегда нужен для backend-проектов.',
                'Добавь healthcheck и проверь запуск compose.',
                '["Что такое volume?", "Зачем healthcheck?", "Как передаются env?"]',
                'manual',
                '{"type": "manual_confirm"}',
                600,
                100,
                0,
                0,
                '{"base_xp": 100}',
                0,
                1.0,
                'not_started',
                null,
                null,
                '{"mock": true, "module": "docker"}'
            ),
            (
                8,
                'Testing',
                'API tests',
                'Проверить backend через HTTP-клиент',
                'Написать минимальные проверки health, profile и roadmap endpoint-ов.',
                'https://www.python-httpx.org/',
                'practice',
                'HTTPX',
                'intermediate',
                70,
                1.5,
                'Тесты помогают не ломать фронтовый контракт.',
                'Можешь проверить API без ручного кликанья.',
                'Тестирование API важно на реальной работе.',
                'Напиши 3 проверки для GET /profile/state.',
                '["Что проверять в status code?", "Что такое contract test?", "Как мокать внешнюю LLM?"]',
                'practice',
                '{"type": "test_task", "min_tests": 3}',
                900,
                110,
                0,
                0,
                '{"base_xp": 110}',
                0,
                1.0,
                'not_started',
                null,
                null,
                '{"mock": true, "module": "api_tests"}'
            ),
            (
                9,
                'Project',
                'Portfolio API',
                'Собрать итоговый backend pet-project',
                'Объединить FastAPI, PostgreSQL, Docker, README и демонстрационные запросы.',
                'Итоговый проект: API учебного roadmap с FastAPI + PostgreSQL',
                'project',
                'Свой проект',
                'advanced',
                180,
                4.0,
                'Итоговый проект закрепляет весь маршрут.',
                'Получаешь проект, который можно показать.',
                'Портфолио важнее сухого списка пройденных курсов.',
                'Собери API с 5 endpoint-ами, схемой БД и README.',
                '["Какая главная бизнес-сущность?", "Как показать проект рекрутеру?", "Что добавить в README?"]',
                'project',
                '{"type": "final_project", "deliverables": ["repo", "readme", "demo_requests"]}',
                1800,
                200,
                0,
                0,
                '{"base_xp": 200, "final_project_bonus": 50}',
                0,
                1.3,
                'not_started',
                null,
                null,
                '{"mock": true, "module": "final_project"}'
            )
    ) AS v(
        step_order,
        skill_name,
        topic_name,
        name,
        description,
        resources,
        source_type,
        source_name,
        difficulty,
        duration_minutes,
        estimated_hours,
        why_this_material,
        skill_result,
        career_value,
        practice_task,
        self_check_questions,
        completion_check_type,
        completion_check_json,
        min_seconds_before_complete,
        xp,
        pending_xp,
        verified_xp,
        xp_policy_json,
        fraud_score,
        streak_multiplier,
        status,
        user_note,
        completed_at,
        item_json
    )
    RETURNING item_id, roadmap_id, profile_id, step_order
),
feedback_insert AS (
    INSERT INTO roadmap_feedback (
        profile_id,
        roadmap_id,
        item_id,
        feedback_type,
        feedback_text
    )
    SELECT
        i.profile_id,
        i.roadmap_id,
        i.item_id,
        CASE
            WHEN i.step_order = 3 THEN 'too_hard'
            ELSE 'useful'
        END,
        CASE
            WHEN i.step_order = 3 THEN 'SQL пока сложноват, хочу больше простых примеров.'
            ELSE 'Формат практики подходит.'
        END
    FROM items_insert i
    WHERE i.step_order IN (2, 3)
    RETURNING feedback_id
),
push_insert AS (
    INSERT INTO motivation_push (
        profile_id,
        roadmap_id,
        item_id,
        push_type,
        tone,
        message_text,
        button_text,
        button_payload,
        scheduled_at,
        sent_at,
        status
    )
    SELECT
        r.profile_id,
        r.roadmap_id,
        i.item_id,
        p.push_type,
        p.tone,
        p.message_text,
        p.button_text,
        p.button_payload::JSONB,
        p.scheduled_at,
        p.sent_at,
        p.status
    FROM roadmap_insert r
    CROSS JOIN (
        VALUES
            (
                4,
                'deadline_warning',
                'duolingo_aggressive',
                'Следующий шаг: схема БД. Закрой его сегодня и забери XP.',
                'Открыть шаг',
                '{"action": "open_item", "step_order": 4}',
                now() - INTERVAL '1 hour',
                null,
                'planned'
            ),
            (
                4,
                'xp_opportunity',
                'neutral',
                'Следующий шаг короткий: схема БД. 120 XP ждут.',
                'К шагу',
                '{"action": "open_item", "step_order": 4}',
                now() + INTERVAL '1 day',
                null,
                'planned'
            ),
            (
                null,
                'return_to_route',
                'soft',
                'Ты держишь streak 4 дня. Не ломай ритм, сделай один маленький шаг.',
                'Открыть roadmap',
                '{"action": "open_roadmap"}',
                now() - INTERVAL '2 days',
                now() - INTERVAL '2 days',
                'sent'
            )
    ) AS p(
        item_step,
        push_type,
        tone,
        message_text,
        button_text,
        button_payload,
        scheduled_at,
        sent_at,
        status
    )
    LEFT JOIN items_insert i ON i.step_order = p.item_step
    RETURNING push_id
),
llm_run_insert AS (
    INSERT INTO llm_run (
        profile_id,
        roadmap_id,
        prompt_name,
        input_json,
        output_json,
        status
    )
    SELECT
        r.profile_id,
        r.roadmap_id,
        'roadmap_generation',
        '{"mock": true, "source": "seed_mock_telegram_123"}'::JSONB,
        '{"mock": true, "status": "seeded"}'::JSONB,
        'success'
    FROM roadmap_insert r
    RETURNING run_id
)
INSERT INTO top_users (
    profile_id,
    period_type,
    period_start,
    period_end,
    rank_place,
    xp_value,
    streak_days,
    completed_items,
    completed_roadmaps,
    username_snapshot,
    display_name_snapshot
)
SELECT
    user_id,
    'weekly',
    CURRENT_DATE - EXTRACT(DOW FROM CURRENT_DATE)::INT,
    CURRENT_DATE - EXTRACT(DOW FROM CURRENT_DATE)::INT + 6,
    3,
    280,
    4,
    3,
    0,
    'test_progressor',
    'Тестовый Пользователь'
FROM profile_insert
ON CONFLICT DO NOTHING;

COMMIT;
